### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by Asenath** [sll552/DiscordBee#1]
Is it possible to add unicode support?
What it is shown now is just a bunch of "????" instead of the right characters, here's an screenshot of how it looks.
![untitled](https://user-images.githubusercontent.com/26794419/35821409-b212c82e-0a87-11e8-9e1f-7bf134bcb8e0.png)

**Comment by sll552** [comment]
As far as my code goes, everything should be Unicode already as its C#, but I can reproduce the problem and opened an issue at discord (https://github.com/discordapp/discord-rpc/issues/119)
