### ISSUE TITLE
Add an Option to Disable the Play Indicator Icons

### ISSUE THREAD

**Issue by Gimzie** [sll552/DiscordBee#102]
The play/pause/stop icons are useful when you have DiscordBee's presence running all the time, but if you have it set to only show in your status when something is being played, then the icons just sit there, cutting into the album artwork space.

Ideally, there would be a toggle as to whether or not the rich presence should use the play status indicators, or simply display the album art. Currently, you can imitate this behavior by deleting the play icons from the Discord Application's assets page, but it only works temporarily, as the images get re-uploaded again eventually.

**Comment by Rings4** [comment]
Not something I'd use but I've seen other forks with this feature so it would be nice for this feature to be added here too.

**Comment by Forstride** [comment]
Would like this as well to show as much of the album artwork as possible.

**Comment by VelocityRa** [comment]
I'd also like an option to _only_ show the playing indicator icon when paused/stopped.
I think I'll implement that too.

**Comment by VelocityRa** [comment]
Done.
