### ISSUE TITLE
Unable to add

### ISSUE THREAD

**Issue by Drogoton** [sll552/DiscordBee#108]
**Describe the bug**
Does not add to MusicBee because something isn't found in the DLL file.

**To Reproduce**
1. Add plugin in Preferences > Plugins

**Expected behavior**
It adds.

**Screenshots**
![image](https://user-images.githubusercontent.com/51866750/147887076-59c70e60-f0a1-4a11-bb99-da3f7eaf4f37.png)

**Environment (please complete the following information):**
 - MusicBee Version: 3.4.7805
 - Plugin Version: 2.0.2

**Additional context**
N/A

**Comment by VelocityRa** [comment]
Not an issue, read the README:
https://github.com/sll552/DiscordBee#microsoft-store-version-of-musicbee

Just restart MusicBee and it will be fine.

**Comment by Drogoton** [comment]
Alright, thanks
