### ISSUE TITLE
elapsed time is not displayed

### ISSUE THREAD

**Issue by x6r** [sll552/DiscordBee#115]
**Describe the bug**
elapsed/remaining time is not displayed even if `Show time` and/or `Show remaining instead of elapsed time` are enabled.

**To Reproduce**
1. enable `Show time`
2. save and refresh
3. no time is displayed
4. enable `Show remaining instead of elapsed time`
5. save and refresh
6. no time is displayed

**Expected behavior**
elapsed or remaining time is shown as it always worked

**Screenshots**
![24_01_2022-02_02_MusicBee_EE3CKp4](https://user-images.githubusercontent.com/36301891/150704052-58c55e44-036d-4996-9804-befeb206b3da.png)

**Environment (please complete the following information):**
 - MusicBee Version: 3.4.7805
 - Plugin Version: 2.1.0

**Additional context**
this only happened in the latest version, it was working as expected in v2.0.2. i have not yet downgraded to recheck but i can do so if required.

**Comment by VelocityRa** [comment]
Weird, I can't repro.

**Comment by x6r** [comment]
the problem is on my end.
