### ISSUE TITLE
i need help with discordbee covers.

### ISSUE THREAD

**Issue by mileinmortal** [sll552/DiscordBee#120]
Basically, someone i know, deleted one cover on discord developer portal, but then the covers didnt show up, neither the pause, etc... So i did a research here, till i find the powershell step, i ask them to do it, then they showed me their leveldb folder, but some files were missing, the person of the issue, and me had the same files, but they had different files.

![imagen](https://user-images.githubusercontent.com/101229232/157351911-5811f56a-e510-4055-b412-1d95b62ee281.png)
they had this files
and i had this files
![imagen](https://user-images.githubusercontent.com/101229232/157351933-6c9ecc0b-30a0-438f-af82-8945c41fa1c7.png)

i did a research but i didnt find anything to help them, i told them to reinstall discord, but it didnt work....

**Comment by sll552** [comment]
Which powershell step are you referring to? *.ldb files are required as those are the ones containing the token. These are normally created when logging into discord after restarting it.

**Comment by mileinmortal** [comment]
they tried to change their acc (deleting the leveldb logging out  but it didnt work, they reinstalled musicbee and discordbee even discord, but still the covers doesnt show up for some reason, we've tried everything but still the covers doesnt show up

**Comment by sll552** [comment]
please see #119 its the same issue so i will close this.
