### ISSUE TITLE
Adding "Listening to" activity instead of "Playing"?

### ISSUE THREAD

**Issue by VojtaNesvadba** [sll552/DiscordBee#121]
I have seen some bots over Discord using their custom "Listening to" status instead of "Playing", is this possible to make also to application such as MusicBee? I have found some python line that could make it possible (I guess, not so into this programming stuff)

`await bot.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name="a song"))`

**Comment by sll552** [comment]
In short no, there is a difference between RichPresence (that's what DiscordBee is using) and Presence (that's what bots can use). also see #3
