### ISSUE TITLE
.dll file missing

### ISSUE THREAD

**Issue by Downflow1320** [sll552/DiscordBee#123]
I am using WIndows store version of musicbee. I downloaded this zip today and I went to plugins settings and clicked add plugin. i selected the zip file but it showed an error and said there is no dll file in the zip file so it wont run. any way to fix this
![Screenshot 2022-05-01 161944](https://user-images.githubusercontent.com/98790735/166163131-ed19470c-e182-4786-bb38-936ee73a811b.png)
?

**Comment by sll552** [comment]
Did you take a look into into the file you downloaded?

**Comment by Downflow1320** [comment]
> Did you take a look into into the file you downloaded?

Yea I figured out the problem. I downloaded the wrong ZIP file.
