### ISSUE TITLE
Despite Uploading, Cover Arts Don't Seem to Show up 

### ISSUE THREAD

**Issue by Fivda** [sll552/DiscordBee#124]
I somehow managed to make cover arts upload properly & automatically again despite the recent changes in Discord's Api and other things (See https://github.com/sll552/DiscordBee/issues/119), but for some reason, the covers don't show up in rich presence.

**Screenshots**
![image](https://user-images.githubusercontent.com/53372693/166505752-ec69c37b-48ac-40ec-a7a1-8b01954d61c9.png)
![image](https://user-images.githubusercontent.com/53372693/166506044-bc755fb0-ea5b-4266-8b42-0e183bd56e74.png)
![image](https://user-images.githubusercontent.com/53372693/166506023-fb728712-a3c4-4c9d-a630-d24a9f6e9b53.png)

**Environment (please complete the following information):**
 - MusicBee Version: 3.4.8033
 - Plugin Version: 2.1.0

**Comment by Fivda** [comment]
...After waiting an hour, the literal instant I post this, it now shows up properly. Seems like waiting a while is still necessary, even after it's been properly uploaded.

**Comment by seanmiles** [comment]
Yes, it usually takes a long time to upload and show up on the developer portal. For future reference if the assets are already uploaded and visible on the Discord developer portal but it isn't showing up on rich presence, sometimes restarting both MusicBee and Discord can help.

**Comment by sll552** [comment]
Also if they are visible in the Developer Portal does not mean they are actually available to use, there is a different index that the client checks which is not necessarily in sync with the Portal.
