### ISSUE TITLE
Custom Button doesn't open expected URL

### ISSUE THREAD

**Issue by DannyyyOnGit** [sll552/DiscordBee#129]
**Describe the bug**
After setting up a custom button and it appearing on Discord Presence. It doesn't seem to work as expected.

**To Reproduce**
1. Set up custom button label and url (see screenshot)
2. Notice button appearing as expected
3. Click button to open url
4. Button doesn't open external browser window

**Expected behavior**
Clicking the button should open your default browser with the expected url.

**Screenshots**
![image](https://user-images.githubusercontent.com/86955470/171621715-50899d48-f52c-4b59-beb1-bb59e978d6ba.png)
![image](https://user-images.githubusercontent.com/86955470/171621736-9b7f811a-bd5e-4b65-8ba8-a3b06ecff617.png)

**Environment:**
 - MusicBee Version: 3.4.7805 P
 - Plugin Version: v2.2.0

**Additional context**
I'm using discord for desktop and not the browser version. The browser console in Discord Canary (Ctrl+Shift+I) doesn't give any info about this either.

**Comment by aikoofujimotoo** [comment]
I'll be checking this more further tonight.

**Comment by DannyyyOnGit** [comment]
> I'll be checking this more further tonight.

Not sure if this is caused by your code though, could be Discord. 
Is there any way I could provide you logs or something useful?

**Comment by aikoofujimotoo** [comment]
> > I'll be checking this more further tonight.
> 
> Not sure if this is caused by your code though, could be Discord. Is there any way I could provide you logs or something useful?

I just confirmed the issue just now. This happens because the other parts of URL like `?=` get URLEncoded. Thus ended up like this.
![image](https://user-images.githubusercontent.com/35658068/171665327-6f556c4b-7e9e-402e-a038-ef3daaaf230c.png)

I'll be making a PR fixing this issue.

**Comment by DannyyyOnGit** [comment]
@aikoofujimotoo @sll552 We might have to re-open this.

It still doesn't work for me on desktop and mobile. This is my config:
![image](https://user-images.githubusercontent.com/86955470/171996787-a414a7af-4c19-4ef6-92d4-264d6e6bbfb5.png)

**Comment by aikoofujimotoo** [comment]
Hmm. I can't reproduce it on my end. If you are trying to open the URL with the same discord instance/account, it will not open as per limitation stated here: https://github.com/Lachee/discord-rpc-csharp/issues/184

Also if you have very long URL, for some reason it will not update/show up the rich presence at all.

**Comment by DannyyyOnGit** [comment]
> Hmm. I can't reproduce it on my end. If you are trying to open the URL with the same discord instance/account, it will not open as per limitation stated here: https://github.com/Lachee/discord-rpc-csharp/issues/184

Alright the instance makes sense. I was only testing using my own account.
