### ISSUE TITLE
Allow a bit more customization with current tracks/durations/etc.

### ISSUE THREAD

**Issue by JBoughter** [sll552/DiscordBee#13]
Just an idea to add a bit more to the configuration for DiscordBee. Allowing to change the formatting of the tracks completely instead of being forced to parentheses, along with being able to move around things regarding the track duration and perhaps add another placeholder for the full length of the song. For example, a template that may look like:

[Artist] - [Album] ([Year])
[TrackTitle] ([TrackNo]) / [TrackCount] (then below add another line)
[CurrentLength]/[TrackLength] (CurrentLength = the 0:00 elapsed, TrackLength = the length of the track itself)

I don't really have any other ideas than that, but it'd be really cool to be able to mess with it a bit more. I always like to mess with mine and see what stuff I can add to it. Thanks!

**Comment by sll552** [comment]
Unfortunately I am bound to the RichPresence API, so I can't add fields or lines etc.
The available fields are documented [here](https://discordapp.com/developers/docs/rich-presence/how-to#updating-presence) and in the picture you can see how the fields correspond to the presence in the client. These fields also have a type so i can only set e.g. partySize to an int. 
![image](https://user-images.githubusercontent.com/6547809/44630266-fe18f780-a95a-11e8-8915-e423ec798cb6.png)

This is very strict and you can't cheat it with for example adding line breaks or something. And there is also a rate limit of 15sec between updates, so you can't have something like `[CurrentLength]`.

I think the current customization options are pretty much the maximum you can get out of this API but if you see any possible improvement I am happy to read it 😉

**Comment by JBoughter** [comment]
Oh wow, had no clue at all that's how it works. Understandable then! A bit of a shame, I hope they add more leeway later at some point and provide some options.
