### ISSUE TITLE
Can't upload new covers anymore

### ISSUE THREAD

**Issue by Fivda** [sll552/DiscordBee#131]
I was able to use custom covers for a while, but for a few days, pretty much near the last time DiscordBee was updated, it doesn't seem like any new assets are being sent to the rich presence assets. Old assets are still there and can be read just fine, it's just there doesn't seem to be any kind of activity when it comes to uploading new ones. I've been stuck at "ASSETS (265 OF 300)" for a while. As you can see i haven't even reached 300.
It works fine with old ones:
![image](https://user-images.githubusercontent.com/53372693/172374786-38bb385b-b5e8-4efe-9b04-f465d417f5dc.png)
But when it's a new cover, it just displays the MusicBee logo.
![image](https://user-images.githubusercontent.com/53372693/172374996-76c4ac9d-7cb9-4543-9681-7d2905e6248c.png)

I did reinstall DiscordBee and i have the latest features, but it doesn't seem like there's anything. Here's my config:
![image](https://user-images.githubusercontent.com/53372693/172375133-47da8294-3208-4e66-9209-a336427942b6.png)

**Environment (please complete the following information):**
 - MusicBee Version: 3.4.8033
 - Plugin Version: 2.2.1

Had a relatively similar issue a few weeks back:
(https://github.com/sll552/DiscordBee/issues/124)

**Comment by DrakeIsBruh** [comment]
same thing

**Comment by metalglove** [comment]
I have the same problem. No assets get uploaded.

**Comment by Terrails** [comment]
Can confirm this too.

**Comment by Miguel-Heijmans** [comment]
I cna't upload covers either, i checked the app for covers but none seem to be uploaded. 2FA is on and i relogged, i closed discord closed musicbee rebooted pc but nothing works. I took a look in the error log for anything related to discord and it seems to be throwing this error: 

"System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'discord.com'"

**Comment by sll552** [comment]
To clear things up, it is not expected to work right now. Discord changed something that broke the way how the uploads are handled. I am working on a replacement which will be finished soon. for more info see #117
