### ISSUE TITLE
Ability to split Artist/Album/Title placeholder fields across 3 lines instead of 2

### ISSUE THREAD

**Issue by n0bodyyouknow** [sll552/DiscordBee#132]
**Is your feature request related to a problem? Please describe.**
There's quite a few track titles and album titles that are ridiculously long, and since there are only two lines available where you can configure the always-displayed track placeholder fields, you are more likely to end up with whichever line you use to show two of the Artist/Album/Title fields getting truncated in the detail popup.

**Describe the solution you'd like**
Is it possible to allow one of the two following options for this?
1. Allow the top line which currently contains the static bold "MusicBee" text to be configurable, so you could (for example) put [Title] on this new first bolded line, put [Artist] on the second line, and [Album] on the third line.  Each of these items gets its own line, so less prone to something getting truncated.  _(This seems to be the approach that the Spotify Discord integration uses, the track title appears in bold where DiscordBee shows the "MusicBee" text.)_
2. Allow use of a newline character in either of the two existing always-displayed lines, which would allow configuring something like:
  [Title] [LineFeed] [Artist]
  [Album]

I understand that neither may be possible due to limitations of the Rich Presence integration mechanism that DiscordBee uses, but here's hoping!

**Comment by sll552** [comment]
> I understand that neither may be possible due to limitations of the Rich Presence integration mechanism that DiscordBee uses, but here's hoping!

Unfortunately thats exactly the case. Both request are not possible to implement. Everything that can be dynamically changed in a Discord Rich Presence, can be changed in the options of the plugin.
I also thought about the newlines when I implemented the layout stuff initially. Unfortunately those are filtered out quite extensively by Discord (I even tried some less common ways to get a newline).

**Comment by n0bodyyouknow** [comment]
Thanks for the reply and clarification!
