### ISSUE TITLE
Use more track properties as placeholders

### ISSUE THREAD

**Issue by kyrie25** [sll552/DiscordBee#136]
**Describe the solution you'd like**
Be able to access (more) track properties as placeholders such as `Type`, `Bitrate`, `Sample Rate`, etc. Currently DiscordBee allows you to use `Encoder` and `TrackDuration` but that's about it

**Additional context**
![image](https://user-images.githubusercontent.com/77577746/177077916-93c87c58-c316-4d07-ab63-7da703d0482c.png)

**Comment by sll552** [comment]
Currently all Tags are supported, those are file properties and should be accessible too via API. I will take a look.
