### ISSUE TITLE
Ability to chose the displayed "playing" status on discord

### ISSUE THREAD

**Issue by L0Lock** [sll552/DiscordBee#141]
**Is your feature request related to a problem? Please describe.**
In Discord, the "playing" status will show that I am playing "DiscordBee". It's fine to be honest, but it could be a nice-to-have feature to be able to customize this field. ÍMHO the main issue of displaying "DiscordBee" is that many people have no clue what it is, and that name itself is not self-explanatory. I don't want people at working thinking I am playing games x)

**Describe the solution you'd like**
Ideally, if the plugins' options could have a field to set the "game" name displayed in Discord, that would be top.

**Describe alternatives you've considered**
Alternatively, a compromise could be to display "MusicBee" of even just "music" instead of "DiscrodBee". Not everyone knows MusicBee, but at least it's more transparent, and "music" even more so; since Discord proceeds the "game name" by "user is playing".

![image](https://user-images.githubusercontent.com/16049822/178254042-c1754514-c66f-4f6d-8089-e46e736e70eb.png)

**Comment by Svarr** [comment]
This can't be done directly via the plugin. You have to create your own discord application and use its App ID in the plugin settings (see the [DiscordBee readme](https://github.com/sll552/DiscordBee#custom-discord-app-id)).

**Comment by sll552** [comment]
Also the Default is already "MusicBee" as it always was. And yes its impossible to change the "playing" to "listening" for example. see #3 for more info.
