### ISSUE TITLE
Allow us to use an Imgur account + our own "application" to have our own independent rate limit

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#145]
Using an anonymous imgur account means you cannot delete anything that is uploaded. Using an account would give us the ability to delete artwork, for whatever reason we may want to do so.

As for rate limits, I think doing something similar to using our own Discord App ID where we use our own Imgur App ID (or however that works for imgur) would give us independence from others and prevent the rate limit from being reached by other people.

**Comment by RegorForgotTheirPassword** [comment]
### If you are having rate limit issues and have not passed the "50 uploads/hr" IP limit then you can:

1. [create your own application on the Imgur API](https://api.imgur.com/oauth2/addclient) (No callback URL works fine)
![image](https://user-images.githubusercontent.com/55347112/179116374-dd86ca1c-d432-42af-bf46-1a6da78739d6.png)
![image](https://user-images.githubusercontent.com/55347112/179116422-c5740431-1ae5-444c-8177-fad881b62a17.png)

2. clone the DiscordBee Repository 

3. change the client ID on line 87 of [DiscordBee.cs](https://github.com/sll552/DiscordBee/blob/master/DiscordBee.cs) (default is "34debbc0ae4077e")
![image](https://user-images.githubusercontent.com/55347112/179116475-6c37be0d-f8ee-4206-bba5-e96467f3d78a.png)

4. build the application using the default built event and replace all necessary files in your MusicBee/Plugins folder

**Comment by BobbyWibowo** [comment]
Lmao yeah, had to do just that myself
First time using it for the day, and the hard-coded client already reported as unhealthy straight away on my end

**Comment by Rings4** [comment]
> The topic of rate limits is also more complex than it seems as there are actually two different limits. One is per IP and one is per Application. So a different Imgur App ID would only help for the second limit, the per IP limit would still hit.

I know lol that's exactly why I suggested you allow us to use our own application ID. So we don't encounter the second limit.

**Comment by sll552** [comment]
I actually didn't think that the limit would be hit that much after the initial storm when the new upload releases. It's about 1250 uploads per day, so actually not a small amount. I guess I underestimated either the usercount of this plugin, or the number of different albums 😅 

I will take a look at adding a more comfortable option than recompiling.

**Comment by Rings4** [comment]
Sounds good! Most people don't listen to entire albums at a time so you'll easily find the limit being reached otherwise. I listen to 80 songs a day on average and sometimes they're playlist shuffles of my top rated songs, meaning 80 tracks with unique artwork. M1
