### ISSUE TITLE
MusicBee UI lockup when Discord is not running

### ISSUE THREAD

**Issue by Svarr** [sll552/DiscordBee#154]
**Describe the bug**
If I start MusicBee with DiscordBee enabled while Discord is not running, MusicBee's UI locks up after two or three songs.

**To Reproduce**
1. Exit Discord if running
2. Start MusicBee
3. Start playing a few songs

**Expected behavior**
MusicBee working normally, i.e. responding to user interaction

**Environment:**
 - MusicBee Version: 3.4.7805
 - Plugin Version: 3.0.3

**Comment by sll552** [comment]
Could you try the newest version (3.1.0), it might fix that problem

**Comment by Svarr** [comment]
I finally got around to testing it and the issue appears to be solved in the current version (3.1.0).
