### ISSUE TITLE
Prioritization of DiscordBee Rich Presence

### ISSUE THREAD

**Issue by inDe-eD** [sll552/DiscordBee#156]
Not sure if it's possible, but seeing that there is now an added option to show the rich presence even when nothing is playing, I'm hoping it might be possible somehow. 

Whenever I launch a game, Discord about 80% of the time decides to show the game as my status rather than MusicBee, even if I was playing music before I launched the game. Is there a way to prioritize it? Whether that be a client-side fix / workaround or if there is some way to add an option to constantly tell Discord that this is the important process to display, I'm not sure. I'm not even sure if it's possible. But, I would prefer to have my music being displayed over my games pretty much all the time.

Also, I could be having an issue, if this doesn't happen for other people. Because as mentioned, I've noticed it doesn't ALWAYS take over my status, which leads me to believe there is some way to get it to work. Either way, I'd love to know if it can be done!

**Comment by VelocityRa** [comment]
What if you start DiscordBee _after_ the game? Maybe it uses the latest one.

**Comment by sll552** [comment]
Unfortunately its not possible to set a priority, AFAIK whatever is setting the presence last wins.
