### ISSUE TITLE
Previous album covers refusing to upload after 3.0.3 was installed. But will remain to upload new covers for newly added albums

### ISSUE THREAD

**Issue by OriginalWayback** [sll552/DiscordBee#158]
**Describe the bug**
I have been using DiscordBee since Version 2.0.2 (January 1st, 2022.) when album covers are directly uploaded into the Application using the Discord Developer Portal. I've just downloaded the latest version, 3.0.3 (August 11th, 2022.) And the previous album covers that were uploaded before no longer display their cover in Rich Presence.

**To Reproduce**
1. Download version [2.0.2](https://github.com/sll552/DiscordBee/releases/tag/v2.0.2)
2. Install version 2.0.2 and set up an application using the [Discord Developer Portal](https://discord.com/developers/applications)
3. Once the application is created, copy the Application ID and paste it into the Discord ID Section in Configure
4. Wait until DiscordBee fully sets up the application. Add an album into Musicbee with a cover. Wait 5-10 minutes for the cover to upload. Then delete the cover in Rich Presence Assets
5. Download [3.0.3](https://github.com/sll552/DiscordBee/releases/tag/v3.0.3) and replace version 2.0.2
6. Add a new album with a different cover. Wait 5-10 Minutes for the cover to upload.
7. Compare Rich Presence and see the error.

**Expected behavior**
The previous album covers uploading to Imgur and displayed in Rich Presence 

**Screenshots**
https://imgur.com/a/97MmtPc

**Environment (please complete the following information):**
 - MusicBee Version: 3.5.8249
 - Plugin Version: 3.0.3

**Additional context**
ImgurUploader Healthy remains True when the previous album is not displaying the cover, and the cache has been deleted before in an attempt to solve the issue. (August 16th, 2022.)

**Comment by sll552** [comment]
Can you check if the missing albums are in the created imgur album (the .album file right nect to the cache)? there should not be a reason why it does upload new covers but not older ones.

**Comment by OriginalWayback** [comment]
> Can you check if the missing albums are in the created Imgur album (the .album file right next to the cache)? there should not be a reason why it does upload new covers but not older ones.

I'm sorry, I have forgotten about this issue I've opened up.

No, as far as I know, they do not show up even if Musicbee launched and the first thing it presented was the old album I've mentioned beforehand. (The Road Part I) As far as I know, the missing albums do not appear in the .album file.
