### ISSUE TITLE
The rich presence is not showing up anymore

### ISSUE THREAD

**Issue by Nekothegamer** [sll552/DiscordBee#160]
**Describe the bug**
the rich presence no longer shows up when you play a song, and it's weird considering it worked a few moments ago 

**To Reproduce**
1. Play a song

![MusicBee_AQoFidT5sB](https://user-images.githubusercontent.com/112352776/187096694-551838a4-b607-44da-a98c-4e36746ceacc.png)

i tried uninstalling it but it doesn't fix the issue, it still doesn't show up.

please help me on this one, it's the reason i use Musicbee in the first place so that i don't have to switch to spotify to show my music.

**Environment (please complete the following information):**
 - MusicBee Version: 3.4.8033
 - Plugin Version: 3.0.3

**Comment by huangdangwibu** [comment]
having the same issue. did you try reinstalling discord and/or the plugin?

**Comment by Sol-Snow** [comment]
Temporary solution:
I deleted the "leveldb" folder in [AppData/Roaming/discord/Local Storage] and logged back on Discord.

I'm not sure if the Rich Presence will break again. Most likely will.

**Comment by huangdangwibu** [comment]
> Temporary solution: I deleted the "leveldb" folder in [AppData/Roaming/discord/Local Storage] and logged back on Discord.
> 
> I'm not sure if the Rich Presence will break again. Most likely will.

i did this. did not work

**Comment by Nekothegamer** [comment]
i have solved this, don't worry y'all

but i have this bigger problem now that i don't understand aswell: https://github.com/sll552/DiscordBee/issues/162

**Comment by huangdangwibu** [comment]
> i have solved this, don't worry y'all
> 
> but i have this bigger problem now that i don't understand aswell: #162
how did you solve it

**Comment by glacialcascade** [comment]
For me, reverting my version of DiscordBee to v1.4.2 fixed it (but v2.0.0 and up don't work).

**Comment by Slug-Cat** [comment]
This version is completely non-functional for me as well. I've reinstalled the plugin, and tried every combination of closing the discord client, logging out, and closing/reopening musicbee I can think of.

**Comment by huangdangwibu** [comment]
stopped working again. mb 3.5.8249

**Comment by Rings4** [comment]
My v2.0.0 version has just stopped working, so I spent the past hour trying everything I can think of, including rebooting my PC 3 times, updating to v3.0.3, using the default app ID, disabling and enabling the plugin, etc.

It just never shows up on discord, at all. Any help?

**Comment by SU042002** [comment]
Mine was working flawlessly too until it just stopped for no reason. Tried reverting to previous updates and did not work. Tried uninstalling and just other methods but nothing I do works :/ This feels like it happens every now and again and its pretty annoying.

**Comment by SU042002** [comment]
Fyi, the older versions do work, they just don't have other functionality like adding album covers etc... These new versions always seem to stop working for me.

**Comment by huangdangwibu** [comment]
discord probably changed up lots of stuff. almost all bd plugins are broken

**Comment by Rings4** [comment]
Hopefully an update can be made to address this.

**Comment by sll552** [comment]
please try https://github.com/sll552/DiscordBee/issues/169#issuecomment-1272325297
