### ISSUE TITLE
Rich presence not work anymore on discordweb after 3.0.3 was installed.

### ISSUE THREAD

**Issue by Mocorongo** [sll552/DiscordBee#161]
It was working a few hours ago and all of a sudden it's not showing the status anymore!

**Comment by SU042002** [comment]
Hey, mine stopped working for a while but it seems to be working now for some reason. What about you?

**Comment by SU042002** [comment]
Never mind, ever since the new discord layout change it seems to not be working properly. It worked for a tiny bit again until it just stopped. Used to work pretty well before

**Comment by Mocorongo** [comment]
> 
Mine stopped permanently and didn't work again, I'll see if another player with rich presence works on Discord Web
