### ISSUE TITLE
Discordbee doesn't accept newer app IDs

### ISSUE THREAD

**Issue by Roseoid** [sll552/DiscordBee#166]
App IDs used to be 18 characters, now they are 19 characters. I have a newer discord account and thus I had to create a new application, and with it's newer ID the length is incompatible.

https://i.imgur.com/j8btzi1.png

**Comment by sll552** [comment]
This was fixed in https://github.com/sll552/DiscordBee/releases/tag/v3.0.2 so update to at least that version
