### ISSUE TITLE
Plugin not showing in Discord

### ISSUE THREAD

**Issue by BrightShad3** [sll552/DiscordBee#169]
DiscordBee is not showing even after following all instructions.

I tried:

1. Re-installing
2. Re-enabling
3. Restarting, Re-logging, adding and removing a game in Discord

Also the Error Log is empty.

I'm using:
MusicBee v3.5.8296
DiscordBee v3.0.3
Windows 10 Pro v10.0.19043

Any ideas on how to fix this?

**Comment by Summer-1999** [comment]
My status is not showing up as well.
I recently upgraded to windows 11, I thought it stopped working after the upgrade but seeing this and issue #160, it probably stopped working for a while and I did not realise that.

I got one error in the log, but I think this is the error upon installing which doesn't matter
```
07/10/2022 22:32:23 - 10.0.22621.0 - 3.4.8033.18564D - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.Plugin.GenerateMetaDataDictionary(String fileUrl)
   at MusicBeePlugin.Plugin.UpdateDiscordPresence(PlayState playerGetPlayState)
   at MusicBeePlugin.Plugin.ReceiveNotification(String _, NotificationType type)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at #=zMnhegC3cZoGqJc9MnQ==.#=zfI$g0dmHvroz()
```

MusicBee v3.4.8033
DiscordBee v3.0.3
Windows 11 Home Single Language, 22H2 build 22621.525

**Comment by florinsdistortedvision** [comment]
Also not working here either, simply broke one day, maybe discord changed some things

**Comment by cudillal** [comment]
Same here on a new laptop with a freshly installed Windows 10 Home 21H2 (DiscordBee v3.0.3, MusicBee 3.4.8033)

**Comment by BrightShad3** [comment]
I think it's a Discord problem more than the plugin one.

**Comment by qqlain** [comment]
Same problem here, I tried with older versions but had no luck. 
MusicBee v3.4.8033
DiscordBee v3.0.3
Win10 21H2

**Comment by Summer-1999** [comment]
> I think it's a Discord problem more than the plugin one.

Probably, but discord presence plugin for vscode still works for me, and it hasn't been updated for months now

**Comment by sll552** [comment]
Could you try this https://ci.appveyor.com/api/buildjobs/9dghwpwh22paebhh/artifacts/DiscordBee-Release--307.zip

**Comment by florinsdistortedvision** [comment]
> Could you try this https://ci.appveyor.com/api/buildjobs/9dghwpwh22paebhh/artifacts/DiscordBee-Release--307.zip

Just tried it, works fine now (including album art). Thank you for the fix

**Comment by Summer-1999** [comment]
> Could you try this https://ci.appveyor.com/api/buildjobs/9dghwpwh22paebhh/artifacts/DiscordBee-Release--307.zip

Worked for

> Could you try this https://ci.appveyor.com/api/buildjobs/9dghwpwh22paebhh/artifacts/DiscordBee-Release--307.zip

Worked for me too!

**Comment by Rings4** [comment]
> Could you try this https://ci.appveyor.com/api/buildjobs/9dghwpwh22paebhh/artifacts/DiscordBee-Release--307.zip

I feel like I'm doing something wrong since it's still not working for me. I just pasted the contents of the zip into the plugins directory for MusicBee. Is that all I need to do? If so, why isn't it working for me?

**Comment by BrightShad3** [comment]
Can confirm it works with me too. Thank you for the quick fix!

**Comment by cudillal** [comment]
Works for me too, thank you!

**Comment by viralhysteria** [comment]
Not working for me. Tried deleting 2.x.x files with no change.
