### ISSUE TITLE
Presence is not updated when it contains long strings

### ISSUE THREAD

**Issue by Fremilia** [sll552/DiscordBee#17]
**Describe the bug**
Presence is not updated when it contains a title string with its length>=115 characters or an artist string with its length>=30 characters (often happens with songs that have several artists).
Don't know if it's a bug from DiscordBee or a limitation from RichPresence tho.

**To Reproduce**
Edit a song title for a string over 115 characters, or an artist for a string over 30 characters, then try to update presence by changing playing song (using default DiscordBee settings).

**Expected behavior**
Presence being updated on Discord.

**Environment**
 - MusicBee Version: 3.2.6827
 - Plugin Version: 1.2.0

**Comment by sll552** [comment]
Actually a bug in the marshaling, but I wrote that thing too so yeah 😅. Will be fixed in a minute.
