### ISSUE TITLE
DiscordBee working on alt account but not main

### ISSUE THREAD

**Issue by lettuceinsalad** [sll552/DiscordBee#172]
**Describe the bug**
On my main account, DiscordBee doesn't show up, but on my alt it does
I've messed around the with the App ID in the configs, it doesn't seem to change anything
I think it might have something to do with a setting enabled on my main account, but I've checked everything and not sure what's different between the two accounts that's causing this difference.
Also, not sure if this is relevant but for some reason on my alt the UI for users is a bit different as you can see in the screenshots

**Expected behavior**
Both accounts working

**Screenshots**
![10_08_22_15_29](https://user-images.githubusercontent.com/65832351/194724377-689dcd22-1ce5-43d8-8e30-9e7516e654af.png)
My main account not showing anything

![10_08_22_15_30](https://user-images.githubusercontent.com/65832351/194724382-fba15365-ee0b-4bb6-8a35-f085ca88b51f.png)

![10_08_22_15_33](https://user-images.githubusercontent.com/65832351/194724442-18e5e1e6-1a93-474b-9153-f773a1b60bc0.png)
My alt account showing it along with different UI

**Environment (please complete the following information):**
 - MusicBee Version: 3.5.81
 - Plugin Version: 3.04

**Additional context**
I had been using the plugin on my main account for around a year when it randomly stopped working around a week ago, I saw the recent post about the plugin not working and downloaded the 3.07 version of the plugin which other people said worked, but still didn't work for me

**Comment by Rings4** [comment]
Similar issue except it just isn't working on any of my accounts.

**Comment by lettuceinsalad** [comment]
Not sure if this is relevant, but if I set the App ID to a rich presence app on my main account, my alt account can still load images. I've also tried this will different alt accounts, all of them work except for my main account.

**Comment by sll552** [comment]
I have no idea what could be causing this. There is no real connection between the plugin and the user, so changing app id or anything won't have an impact.

Are the settings for the game activity the same on all accounts (is musicbee registered as a "game")?

**Comment by lettuceinsalad** [comment]
Yes, every account has MusicBee available to click when I go to "Registered Games."
![image](https://user-images.githubusercontent.com/65832351/194871605-e2ffff51-e488-4a7a-a999-77ae2f67a1a6.png)

**Comment by lettuceinsalad** [comment]
I reinstalled the DiscordRPC.dll file again, and now it works. Thanks for your help.
