### ISSUE TITLE
Show MusicBee/DiscordBee status under 'Active Now' section

### ISSUE THREAD

**Issue by samplegitest** [sll552/DiscordBee#183]
**Is your feature request related to a problem? Please describe.**

When listening to music, the plugin does not show any status under the Active Now sidebar on the Friends page.

![discordbee-active-now](https://user-images.githubusercontent.com/119043914/203957221-5c3f9881-4f7e-46d9-a10c-64634ba696d4.png)

**Describe the solution you'd like**
If possible, display info about the currently playing song in the Active Now section. This screenshot shows how it looks with Spotify, for example: https://beebom.com/wp-content/uploads/2021/01/spotfiy-status-in-discord-active-now.jpg

**Describe alternatives you've considered**
N/A

**Additional context**
Didn't have any success finding information about what controls whether games/apps show on that section. I also didn't notice any setting that would prevent that from working on my account.

**Comment by sll552** [comment]
I am afraid that there is nothing I can do about that. It's a Rich Presence so it should work the same as games that use that API.
