### ISSUE TITLE
Custom RichPresence Logo

### ISSUE THREAD

**Issue by WeebSenpai** [sll552/DiscordBee#21]
How about an option to add a custom RichPresence Logo? Not sure if it's possible with the current DiscordRPC, or is it possible to change to a custom DiscordRPC applicationID? Might be unreasonable because there's almost no way to edit a .DLL file, but would be a cool feature :)

**Comment by sll552** [comment]
This has been discussed in https://github.com/sll552/DiscordBee/issues/3#issuecomment-397065656

In short:
No, its not possible due to limitation by Discord.
No, I do not plan to support custom App IDs. If you want that, fork this repo and run your own version (it's simple)
