### ISSUE TITLE
Feature Request - Option to not override playing game information

### ISSUE THREAD

**Issue by xhocquet** [sll552/DiscordBee#230]
**Is your feature request related to a problem? Please describe.**
Hey there, the plugin works well however it hides the game I'm playing. 

**Describe the solution you'd like**
I would like a new option for the following:
When I'm playing a game, I'd like for the game to appear in Discord as usual. If Discord does not have anything else showing, then it can show Musicbee + DiscordBee information

Do you think this would be possible?

**Comment by sll552** [comment]
Unfortunately this is not possible see https://github.com/sll552/DiscordBee/issues/156

**Comment by xhocquet** [comment]
Thanks for the response, seems like it's a feature request @ Discord too - https://support.discord.com/hc/en-us/community/posts/360045758192-Rich-Presence-Priorities
