### ISSUE TITLE
[Feature Request] 3rd line editing

### ISSUE THREAD

**Issue by Zetvue** [sll552/DiscordBee#232]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to be able to edit the 3rd line (where the elapsed/remaining time is).
![image](https://github.com/sll552/DiscordBee/assets/87939327/21688fb3-7ff5-44c1-abbb-e23758bfa5f9)

**Describe alternatives you've considered**
No other RPC plugins I know of do this. Not even Foobar2000's.

**Additional context**
No additional context.

**Comment by UrbanCMC** [comment]
I'm pretty sure that isn't actually an editable line.
As far as I know Discord just receives a timestamp when the track started (or when it will end if you set it up the other way around) and calculates the time on the client looking at it. Doing it any other way would be insanely wasteful, anyways.

**Comment by sll552** [comment]
Basically what @UrbanCMC said, that is also why nobody else is doing it 😉 

So unfortunately no it's not possible to have this freely editable
