### ISSUE TITLE
Discordbee custom button not appearing anymore

### ISSUE THREAD

**Issue by Razen1994** [sll552/DiscordBee#241]
**Describe the bug**
Hiya! Hope this project is still active since i love it and use it a bunch! So i noticed that recently the profile in discord got more compact (I assume that was a discord update) and since then the custom button is just gone. 

**To Reproduce**
Try to enable the button and its just not visible anymore.

**Expected behavior**
The custom button appearing.

**Screenshots**
![image](https://github.com/sll552/DiscordBee/assets/114489732/2e4a7a52-383a-41d4-9e67-d679bfb3c4c1)
![image](https://github.com/sll552/DiscordBee/assets/114489732/cbffe679-59ff-410d-8e32-a99d353cc1f8)

**Environment (please complete the following information):**
-Latest version of discord + latest version of musicbee + discordbee

**Additional context**
Any help would be much appreciated and thank you for all the hard work you put into this plugin!

**Comment by Rings4** [comment]
Damn, I just noticed this as well. I was just thinking about how much thought I put into my button, where it would show my play history when the song has 1+ listens, otherwise show the song's last.fm page with 0 plays, and went to try clicking it for the first time in forever, only to see it doesn't exist anymore.

Is this something that this plugin can bring back, or did Discord just kill this feature entirely?

**Comment by Razen1994** [comment]
> Damn, I just noticed this as well. I was just thinking about how much thought I put into my button, where it would show my play history when the song has 1+ listens, otherwise show the song's last.fm page with 0 plays, and went to try clicking it for the first time in forever, only to see it doesn't exist anymore.
> 
> Is this something that this plugin can bring back, or did Discord just kill this feature entirely?

I've seen that Spotify still has buttons so i hope that it's possible to bring back. I'm no programmer though so to be entirely honest i have no idea if its just cause it's Spotify and they are allowed to or if maybe the plugin just needs an update.

**Comment by Rings4** [comment]
I figured it out. You can no longer see your own custom button, but the button still indeed works. It's a weird discord thing. 

I just set up MusicBee for my friend and copied over my DiscordBee settings (changing my last.fm to his ofc) and his button shows.

![image](https://github.com/sll552/DiscordBee/assets/32050292/e6f23db9-64fc-4e05-81b4-9c7149f7bf9f)

**Comment by Razen1994** [comment]
> I figured it out. You can no longer see your own custom button, but the button still indeed works. It's a weird discord thing.
> 
> I just set up MusicBee for my friend and copied over my DiscordBee settings (changing my last.fm to his ofc) and his button shows.
> 
> ![image](https://private-user-images.githubusercontent.com/32050292/347659946-e6f23db9-64fc-4e05-81b4-9c7149f7bf9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4Nzc4MzksIm5iZiI6MTcyMDg3NzUzOSwicGF0aCI6Ii8zMjA1MDI5Mi8zNDc2NTk5NDYtZTZmMjNkYjktNjRmYy00ZTA1LTgxYjQtOWM3MTQ5ZjdiZjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEzMzIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZjAzMmRiOGRjMGMzZGMwMjBlODRmYmIxMGE0NDg2NzkxNjRlZDU5YzcxNWI0MTJmZDRiZTg1YWE2MWNmZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CKpYn-HH0ziIGA01vBAMUGQxaL4tJMVReo7laslOIyw)

Hot damn you are actually correct! Nice catch and thank you! Was bugging me quite a lot but it seems Discord is just doing Discord things...
