### ISSUE TITLE
The custom buttons don't appear anymore on Desktop client and the Time for the music track too 

### ISSUE THREAD

**Issue by Elasder123** [sll552/DiscordBee#246]
The custom buttons don't appear anymore on the new Desktop Discord client and the timer too
![bilde](https://github.com/user-attachments/assets/b746b51f-da3b-43d1-9096-58af16723eff)
As you can see, it works, but the only things missing are the custom button and song timer. :/

**Comment by Benzeel** [comment]
this is a discord bug. they do not show for you *only* i figured out :/

**Comment by Elasder123** [comment]
> this is a discord bug. they do not show for you _only_ i figured out :/

Found out it does show up in the VC status
![bilde](https://github.com/user-attachments/assets/5480a801-4441-46d4-8e62-ca1e8e0558ac)

and in the profile details in Dms 
![bilde](https://github.com/user-attachments/assets/c32d785a-5ada-4759-8b98-d8310ed622aa)
(Can't really show it tho cuz I can't check myself lol but yea)

**Comment by Elasder123** [comment]
Apparently, the button is visible to other users besides yourself 
So this issue is resolved
