### ISSUE TITLE
Cannot Change (_ of _) Field

### ISSUE THREAD

**Issue by Gimzie** [sll552/DiscordBee#27]
DiscordBee seems to ignore anything I put into the (_ of _) field in the configuration menu, leading it to always show "(1 of 1)" by the bottom field.

**To Reproduce**
1. Go into the configuration menu for DiscordBee.
2. Change the two fields enclosed in parentheses to anything else.
3. Observe as the field does not change on Discord.

 - MusicBee Version: 3.3.7310
 - Plugin Version: v1.3.0

I think this is related to the library update, because DiscordBee v1.2.1 does not have this issue and I am currently using it without any problems.

**Comment by sll552** [comment]
Thanks for reporting,

indeed it seems like the new library is handling the case of a party size of 0 (this happens when you set something that is not a number for one of the (x of x) fileds) differently than it was before. I will try to fix this asap

**Comment by sll552** [comment]
Could you please try the following version, it should fix your problem: https://ci.appveyor.com/api/buildjobs/8pq3v702s6qsbgy5/artifacts/DiscordBee-Release--67.zip

**Comment by Gimzie** [comment]
Sorry for the late response, but I tried your build and it seems to work fine! Thank you for the quick response, I'll go ahead and close this now.
