### ISSUE TITLE
how do i remove the track number?

### ISSUE THREAD

**Issue by bar-dot** [sll552/DiscordBee#29]
replacing it with " " doesnt work

**Comment by sll552** [comment]
I am just guessing that this is a possible duplicate of #27 

Could you please try the version linked in https://github.com/sll552/DiscordBee/issues/27#issuecomment-594153050

**Comment by bar-dot** [comment]
> I am just guessing that this is a possible duplicate of #27
> 
> Could you please try the version linked in [#27 (comment)](https://github.com/sll552/DiscordBee/issues/27#issuecomment-594153050)

that fixed it :D thanks
