### ISSUE TITLE
Album cover and "listening" instead of playing

### ISSUE THREAD

**Issue by llkiriell** [sll552/DiscordBee#3]
Hi, great job with the plugin, thanks.
Will the album cover be implemented? and "Listening" instead of "Playing"?
In the _JS API_ there is the **[.setPresence](https://discord.js.org/#/docs/main/stable/typedef/PresenceData)** method that has the attribute "**game.type**" where you can change **_"playing"_** to **_"listening"_**. Is there an identical method in the API that has been used in this plugin?
![game type](https://user-images.githubusercontent.com/12781734/36624870-23b5b162-18e3-11e8-921e-789ddbb47b98.png)

**Comment by sll552** [comment]
I am using the DiscordRichPresence which is different to the "normal" Presence that is described in the JS library you linked. The available fields for RichPresence are described [here](https://discordapp.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields) and there is also a picture that shows which value is which in the Discord UI. Unfortunately it's currently not possible to set the type to something else than "Playing" when using [RichPresence](https://github.com/discordapp/discord-rpc). There is an issue that tracks this at Discord https://github.com/discordapp/discord-rpc/issues/71

For Album cover it's the same, it is currently not supported but there is also an issue (https://github.com/discordapp/discord-rpc/issues/70) for this feature at Discord and I will implement that as soon as it is supported.

I will keep this issue open to track this request.

**Comment by JBoughter** [comment]
What if you tried to use Last.fm covers for the covers instead? It'd probably be a whole different pickle alone and it'd be easier to wait for the issue on RPC to be addressed, but it's something.

**Comment by sll552** [comment]
I don't know what you mean with using Last.fm covers.

Currently it is only possible to display pictures that are preuploaded (by me) to the Discord developer dashboard. There is also a limit of 150 pictures for the app. This is documented [here](https://discordapp.com/developers/docs/rich-presence/how-to#your-new-developer-dashboard).

**Comment by JBoughter** [comment]
Understood. I had no clue how images worked, so I was just taking a guess.

**Comment by jugges** [comment]
@JBoughter Same, looked through the source code, trying to figure out how to implement a changing artwork but could not figure out how the hell the text "logo" or "play" etc are responsible to changing image.

Thanks for keeping us informed op (:

**Comment by aphextwins** [comment]
You made an amazing plugin, it works, its customizable. thanks!
The only thing keeping me from using it is the MusicBee branding.

I dislike the icon and name, eventhough its the best music player.

can you perhaps make it so I can give my own Application ID that i make myself on https://discordapp.com/developers/applications/me ?
![untitled](https://user-images.githubusercontent.com/37220822/41374366-42a7b31a-6f53-11e8-853e-6808ed222085.png)

I just want people to know im listening to music, and if they click my card, what song. like that (mockup)

**Comment by sll552** [comment]
Well I don't think this is a use case I want to support.
But nonetheless you are free to install Visual Studio Community (it's free), clone/fork this repo, change the AppID in the code and press the compile button. It should even work out of the box to just press the "Run" button in VS and it should install your version of the Plugin if MusicBee is installed in the default Place.
The only downside would be that you would have to merge new features manually and build again.

**Comment by lilbud** [comment]
Instead of having to upload images to the servers. Could the artwork be read directly from the tag in the music file? Or maybe show art in the music file folder named something like cover.jpg?

I know next to nothing about code, so I could be talking nonsense.

**Comment by wopian** [comment]
@lilbud no. The images have to be explicitly uploaded in the application's settings. It can't display arbitrary images. 😢

**Comment by plskillmeirl21** [comment]
is there any way to modify the "MusicBee" above the artist name and title?

**Comment by sll552** [comment]
@plskillmeirl21 unfortunately there is currently no way to change this. This is the name of the App that is registered to Discord, basically it's the name of the "game" you are playing.

I will now lock the conversation as there are only the same questions over and over again. I will update this issue when Discord decides to implement the needed feature.
