### ISSUE TITLE
Rich Presence stops if it hits character limit

### ISSUE THREAD

**Issue by Kirdock** [sll552/DiscordBee#31]
**Describe the bug**
Rich presence stops working (displayed as "stopped" or it is closed) when a certain character limit is reached (about 128) for "details" or "state" field.

**Expected behavior**
- Trim to 128 characters or trim to 125 characters and add "..."

**Environment**
 - MusicBee Version: [3.3.7367]
 - Plugin Version: [1.3.1]

**Comment by sll552** [comment]
Yeah I guess I expected too much from the new lib to handle such cases... 

I will fix this asap, thanks for reporting

**Comment by Kirdock** [comment]
Still bugged. This does not work, for special characters.

example text (too long):
_Makayla Phillips - 「僕のヒーローアカデミア THE MOVIE ヒーローズ:ライジング」オリジナルサウンドトラック_

result text (130 characters; still too long):
_Makayla Phillips - 「僕のヒーローアカデミア THE MOVIE ヒーローズ:ライジング」オリジナルサウンド�_

**Comment by sll552** [comment]
Well, seems I was a little too fast with the release, I will look into that.
But its not crashing anymore, right?

**Comment by Kirdock** [comment]
It is as the same as before when using special characters. Unhandled Exception at line 250 in DiscordBee.cs, string too long. So yeah it crashes.

My temporary solution:
```csharp
private string LimitByteLength(string input, int maxLength)
{
    return new string(input
        .TakeWhile((c, i) =>
            Encoding.UTF8.GetByteCount(input.Substring(0, i + 1)) <= maxLength)
        .ToArray());
}

...
return LimitByteLength(input, 128);
```

**Comment by sll552** [comment]
I guess the solution is much harder because of how unicode works ... there are unicode chars which are actually two elements in the byte[] and I don't know if `toArray` handles that. I guess thats the problem of the solution right now.

I will try to figure out a way to fix this for all of those cases. But your 2nd suggestion looks like a good starting point, thanks for that.

**Comment by sll552** [comment]
Ok so I got something I guess, please test this: https://ci.appveyor.com/api/buildjobs/f55p5uek6vj7k3s4/artifacts/DiscordBee-Release--86.zip

**Comment by Kirdock** [comment]
Seems like it works now.

- No crashes
- Trim to 128 works
- Tested several files with length above and below 128
- Tested for "details" and "state" field, no problems

**Comment by sll552** [comment]
Thanks, released with https://github.com/sll552/DiscordBee/releases/tag/v1.3.2
