### ISSUE TITLE
Discord only shows 'playing musicbee'

### ISSUE THREAD

**Issue by demon326** [sll552/DiscordBee#35]
**Describe the bug**
It only shows 'playing MusicBee' and not the song and or artist.

**Expected behavior**
Discord should show musicbee as status, but that is not happening.  Plugin has been installed as instructed.

**Screenshots**
![discord-status-not-working](https://user-images.githubusercontent.com/362394/78451417-d38a3700-7685-11ea-8e76-07a1eda87c8e.jpg)
![discord-status](https://user-images.githubusercontent.com/362394/78451419-d4bb6400-7685-11ea-8794-62770e90789f.jpg)

**Environment (please complete the following information):**
 - MusicBee Version: MusicBee 3.3.7367

 - Plugin Version: latest as of 04/04/2020
 - Windows 10 latest

**Comment by sll552** [comment]
As I cannot reproduce this:

1. Was it a clean install or update of the plugin?
2. Please take a look at "Preferences -> Plugins" there should be a discordbee entry but disabled, what happens when you try to enable the plugin in this dialog?
3. Try to delete the DiscordBee-master folder in your plugins directory.
4. Is there anything related to the plugin in the error log (Help -> Support -> View Error Log)?

**Comment by demon326** [comment]
1) Clean install, i even tried and older version
2) Its enabled by default and it looks like the musicbee side works, as the placeholders got data in there.
![discordbee-data-working](https://user-images.githubusercontent.com/362394/78469058-a4270900-771d-11ea-8119-385111c5ad2e.jpg)

3) that was just an empty folder, just forgot to delete it when i took the screenshot.  Deleting it does not help.
4) the error logs are empty, thus no errors to be reported.

I have reinstalled both Musicbee as discord and the same issue persists. I suspect Musicbee cannot communicate with discord. 

I even tried with a clean virtual windows 10 machine with only discord and musicbee installed and that has the same effect. I did this to rule out any config issue.

**Comment by sll552** [comment]
Try to remove musicbee from the games list in discord.
Do you have any discord addons installed (e.g. betterdiscord)?

**Comment by demon326** [comment]
> Try to remove musicbee from the games list in discord.
> Do you have any discord addons installed (e.g. betterdiscord)?

Removed musicbee on the discord side of things a few times, it stays the same.
No addons have been installed. It like i said, it also happens in a clean envirement, a VM win 10 box with only discord and musicbee in there default states. 

I don't need discord nitro, do i?  because if that would be the case, we'd be running in circles.

**Comment by sll552** [comment]
No, no need for nitro.

I will try to replicate this in a clean VM in the evening, but its a really strange problem because it seems like the plugin is not crashing or anything and its happening on a clean VM.

If you don't like to wait, the only thing that I think could yield a hint would be that you install visual studio, open this project and run musicbee through the debugger.

**Comment by demon326** [comment]
i'm **not** using the windows store version of both apps.  i'm using the installer files downloaded from there websites.

I made a debug log and i hope i got it right:
Without plugin enabled: 
`The thread 0x2208 has exited with code 0 (0x0).`

With plugin enabled:
```
Exception thrown: 'System.FormatException' in mscorlib.dll
Trace: Enqueue Command: DiscordRPC.RPC.Commands.PresenceCommand
Exception thrown: 'System.FormatException' in mscorlib.dll
The thread 0x55a8 has exited with code 0 (0x0).
Trace: Attempting to send payload: SetActivity
Trace: Sending payload: SetActivity
Trace: Sent Successfully.
Trace: Ending Read
Trace: Read 346 bytes
Trace: Read a frame: Frame
Trace: Starting another read
Trace: Begining Read of 16384 bytes
Trace: Read Payload: Frame
Trace: Handling Response. Cmd: SetActivity, Event: 
Trace: Enqueued Message, but queue size is 0.
The thread 0x47a0 has exited with code 0 (0x0). --> happens around the 10 second mark of the song
```

After about the last error message the log debug stays where it is, unless i pauze/stop and so on.

**Comment by sll552** [comment]
there should be much more output, interesting would be everything around and after something like this:
```
Trace: Attempting a new connection
DiscordBee loaded
Trace: RPC Connection Started
Trace: ============================
Trace: Assembly:             DiscordRPC, Version=1.0.150.0, Culture=neutral, PublicKeyToken=null
Trace: Pipe:                 DiscordRPC.IO.ManagedNamedPipeClient
Trace: Platform:             Microsoft Windows NT 10.0.18363.0
Trace: applicationID:        409394531948298250
Trace: targetPipe:           -1
Trace: POLL_RATE:            1000
Trace: _maxRtQueueSize:      512
Trace: _maxRxQueueSize:      0
Trace: ============================
Trace: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
Trace: ManagedNamedPipeClient.Connection(-1)
Trace: Connection Attempt 0 ()
Trace: Attempting to connect to discord-ipc-0
Trace: Waiting for connection...
Trace: Connected to discord-ipc-0
Trace: Done. Result: False
```
I have also habe the messages you posted so I still have no clue what could be the problem here. Have you tried other songs?

**Comment by demon326** [comment]
Hi, it looks like did not got the full log, retried this time and got more output:
https://pastebin.com/WfXTsLWY

Tried a few other songs and it seems its the same issue. its strange that it only happens on my clients, but you cannot reproduce it.  Even stranger that it happens in a clean windows install.

**Comment by demon326** [comment]
I tried a new account and that gives the same issue. But i'v been thinking, since it works for 99% of the users, it has to be a 'hardware issue' if it happens in a clean vm install. 

Could it be that one of those patches for the intel vulnerabilities is causing some kind of issue? The last bios flash i did just contains 'microcode updates and fix for Intel ME for security vulnerabilities'. 

Maybe you could upload the VM instance(i know, its huge), so i can see if it is really a HW issue or not :)

**Comment by sll552** [comment]
I do not suspect an actual hardware issue, those patches should not cause any poblem. I think there is some part of your environment that`s special and that I am missing here. Are you using any "Anti-Virus" or "Internet Security" software? 

I guess uploading the whole VM is a bit much but I will try to get all the steps I did written down or maybe a screencast, when I get off work. The base image I used was the developer VM from Microsoft for VMware https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by demon326** [comment]
![itworks](https://user-images.githubusercontent.com/362394/78652561-2cdeaa00-78c2-11ea-92ea-0aca05657e08.jpg)

Out of nowhere it seems to be working like expected, typical :). Just one more question:  Will it always just show 'playing musicbee' on the left side, when in DM mode?

**Comment by sll552** [comment]
😄 glad that it is working now. I will close the issue.

Yes unfortunately I cannot change that, see #3 for more info.
