### ISSUE TITLE
Discord does not require MusicBee to be a game for Rich Presence.

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [sll552/DiscordBee#37]
**Describe the bug**
In the README.md, you state that you need to add MusicBee as a game in Discord. You don't.

**To Reproduce**
1. Install DiscordBee
2. Done

**Screenshots**
Rich Presence working: ![Rich Presence](https://user-images.githubusercontent.com/54776821/83412535-24ae7100-a412-11ea-9aaa-231af89d485e.png)
Proof I had no game selected: ![No game selected](https://user-images.githubusercontent.com/54776821/83412533-237d4400-a412-11ea-9d72-af98b40f3278.png)

**Environment:**
 - MusicBee Version: 3.3.7367
 - DiscordBee Version: 1.3.2

**Comment by sll552** [comment]
You are right, I guess it changed since I wrote the README.
