### ISSUE TITLE
Play/Pause Icons

### ISSUE THREAD

**Issue by heyekto** [sll552/DiscordBee#39]
[https://hizliresim.com/ENPtEN](Photo Link) Check This. Play/Pause Icons bad for me. Can i change these icons?
Or can I remove it?

**Comment by sll552** [comment]
Just like the Icon those can only be changed globally and not by user. Same for removing them altogether.

If you think you found some better suited icons, I am open for suggestions. But keep in mind that such images must have a license that permits the usage for this cause.

**Comment by chusome** [comment]
Like this

>

**Comment by sll552** [comment]
I don't see a picture (maybe because you answered via mail), and please also share the source

**Comment by chusome** [comment]
ah true, wait [https://image.flaticon.com/icons/png/512/27/27185.png](url)

**Comment by sll552** [comment]
yeah looks nice but when you look at the license https://www.freepikcompany.com/legal#nav-flaticon-agreement it says 

> The content in the Flaticon Content or any derivative work is not used or included (in whole or in part) in a database, archive or in any other media/stock product, collection, set of clips, or library, for distribution or resale or used in any other way that could prevent or limit future visits or downloads from the Website;

Which at least to me (I am no legal expert) seems like its forbidden to embed any icons from that website. So unfortunately this is not useable.

**Comment by chusome** [comment]
ah buddy, nvm

sll552 <notifications@github.com>, 25 Haz 2020 Per, 15:14 tarihinde şunu
yazdı:

**Comment by VXsz** [comment]
I have created a little icon packs for this [Playingback - Paused - Stopped]
And I really don't like the current ones with that blue background, kinda ruins the rich presence

![White-Stopped](https://user-images.githubusercontent.com/34054757/96954685-90e25c00-14fc-11eb-85f0-6ef8eb2a791e.png)
![Black-Paused](https://user-images.githubusercontent.com/34054757/96954687-917af280-14fc-11eb-8bd0-a5adfe5873d0.png)
![Black-Playback](https://user-images.githubusercontent.com/34054757/96954688-92138900-14fc-11eb-9a16-fc8ab421eaf7.png)
![Black-Stopped](https://user-images.githubusercontent.com/34054757/96954689-92ac1f80-14fc-11eb-8866-1f4bd438a43c.png)
![White-Paused](https://user-images.githubusercontent.com/34054757/96954692-92ac1f80-14fc-11eb-9c96-ae0d3b926e7f.png)
![White-Playback](https://user-images.githubusercontent.com/34054757/96954693-9344b600-14fc-11eb-9e98-bd620ce9352e.png)

And these are the Illustrator projects if you need them or want to adjust something
[DiscordBee_Icons.zip](https://github.com/sll552/DiscordBee/files/5427245/DiscordBee_Icons.zip)

**Comment by sll552** [comment]
Thanks for your effort, unfortunately they have to be at least 512x512px or even better 1024x1024px. If you can export them with a higher res i will upload them to try them out and see how they look in the client. I would do it myself but I do not own Adobe Illustrator.

**Comment by VXsz** [comment]
I've exported them in 1024x1024, if you need anything else let me know 👍 

Black:
---
![Black-Playback 1024px-1024](https://user-images.githubusercontent.com/34054757/97137967-27ff1c00-1768-11eb-9fea-b8dc4db582ef.png)
----
![Black-Paused 1024px-1024](https://user-images.githubusercontent.com/34054757/97137966-27668580-1768-11eb-8d3e-6693e5d73c0c.png)
----
![Black-Stopped 1024px-1024](https://user-images.githubusercontent.com/34054757/97137968-2897b280-1768-11eb-81e5-d81c9a6ed835.png)


White:
----
(Playback)
![White-Playback 1024px-1024](https://user-images.githubusercontent.com/34054757/97138013-42d19080-1768-11eb-87a4-fd0874080ec0.png)
----
(Paused)
![White-Paused 1024px-1024](https://user-images.githubusercontent.com/34054757/97138017-45cc8100-1768-11eb-8697-64c7fa3c54f3.png)
----
(Stopped)
![White-Stopped 1024px-1024](https://user-images.githubusercontent.com/34054757/97138023-46fdae00-1768-11eb-81df-1beb18af586d.png)

**Comment by mewbit** [comment]
Its good, ty!

VXsz <notifications@github.com>, 26 Eki 2020 Pzt, 08:52 tarihinde şunu
yazdı:

**Comment by sll552** [comment]
I used the white ones, beacause black looks kinda off on the blueish background. Let me know what you think. 

@VXsz Would you like to create a pull request with the uploaded images and source (.ai) files? Just upload them into a folder just like the screenshots. This way you will be listed as contributor and the images will be part of this project.

**Comment by mewbit** [comment]
i like it 😋🙏🏻

27 Eki 2020 Sal 01:37 tarihinde sll552 <notifications@github.com> şunu
yazdı:

**Comment by sll552** [comment]
As it seems that the icons are accepted and look nice, I would like to close this issue.

@VXsz  Before I do this, is it ok to add the icons and the sources to this repo? Your authorship will be attributed of course. If you would like to upload them yourself please open a pull request (all steps can be done in Github via browser).

**Comment by heyekto** [comment]
thanks sll552 for your help and your discord rich presence 🙏🏻

**Comment by VXsz** [comment]
@sll552 Sure, I'm not sure how to make a pull request (new to GitHub) but do as you like with the sources, they were made for this project (and it didn't take much time to create), tho I'd recommend making them bigger, I think they are on the small side on discord presence

**Comment by heyekto** [comment]
and thank you @VXsz for nice icons 🙏🏻
