### ISSUE TITLE
Japanese Characters display as "?"

### ISSUE THREAD

**Issue by natemonster321** [sll552/DiscordBee#4]
![unknown 1](https://user-images.githubusercontent.com/12738442/37189790-1609d8f4-2324-11e8-9626-d0fdb9240a4f.png)
 As seen in the image above, the extension shows English just fine, but Japanese is displayed as a "?". The artist should display as "ギガP feat. れをる", and the album should display as "極彩色".

**Comment by sll552** [comment]
For me it is displaying correctly, what version are you using?
![image](https://user-images.githubusercontent.com/6547809/37226054-ff61a36a-23d8-11e8-81d3-2963e69efe87.png)
![image](https://user-images.githubusercontent.com/6547809/37226155-58f22a8a-23d9-11e8-9bed-38bc17f0194b.png)

**Comment by natemonster321** [comment]
Oof, my bad. I thought I was using the latest version, but it turns out I was on 1.0.1. Sorry about that.
