### ISSUE TITLE
Spotify-like behavior?

### ISSUE THREAD

**Issue by TheKojukinator** [sll552/DiscordBee#51]
Sorry if this counts as a dupe, but since #3 is locked, and the last response is from a couple of years ago, I'm checking in again about whether this is possible.

![image](https://user-images.githubusercontent.com/30471780/100925662-4adfc700-34b0-11eb-99d7-88463dff760b.png)

Mainly these points:

- `Listening to [application]` under the user as well as the top line in the popup.
- Album Art visible for the icon.
- Three rows for info, so it is not horizontally cluttered.
- Progress bar along with time played and track length on the edges, or these can be customizable like the other fields.

Thanks!

**Comment by sll552** [comment]
There is no change, and rest assured I have not forgotten about it. I have subscribed all relevant Discord developer issues but no update there. So unfortunately still not possible.
