### ISSUE TITLE
Rich Presence not displaying in both Canary and Release

### ISSUE THREAD

**Issue by ev3commander** [sll552/DiscordBee#54]
**Describe the bug**
If running both Discord Canary and Discord release version with different accounts, Rich Presence only displays in the Canary account.

**To Reproduce**
1. Open both Discord and Discord Canary on different accounts
2. Start MusicBee with DiscordBee
3. Add MusicBee as a game to both
4. Only see rich presence on the Discord Canary account

**Expected behavior**
Display it on both accounts

**Screenshots**
On the release build: 
![image](https://user-images.githubusercontent.com/11969863/103223134-96d92c80-48f3-11eb-8488-facc3f95e2c5.png)
On canary:
![image](https://user-images.githubusercontent.com/11969863/103223189-ace6ed00-48f3-11eb-857d-2c0ae1def809.png)

**Environment (please complete the following information):**
 - MusicBee Version: 3.4.7568
 - Plugin Version: 1.4.0

**Additional context**

**Comment by sll552** [comment]
Does this work with other Rich Presence Programs/Games (e.g. League of Legends, etc.)?

**Comment by ev3commander** [comment]
I tried it with another program which seems to have only added the rich presence to the release version account, so maybe it's possible to configure which one gets it, or that it's random? I have no clue how rich presence works though.

**Comment by sll552** [comment]
My guess would be that the last or first client that has been started gets the presence. I will check if there is something to configure on my side but I have never come across some setting like this.

**Comment by sll552** [comment]
I checked and there seems to be no way for me to control which clients gets the presence. I consider running both clients in parallel as a non-supported usecase for this plugin. As long as it works on both clients if each of which is running alone I will not put more time into this.
