### ISSUE TITLE
Allow manually setting client id so users can add their own album arts

### ISSUE THREAD

**Issue by aaronlink127** [sll552/DiscordBee#57]
**Is your feature request related to a problem? Please describe.**
Related to #3 in that this issue relates custom album arts

**Describe the solution you'd like**
Allow users to choose their own client id rather than the built in one, as this would allow users to upload their own album covers to their specific instance of the app. It would just use the album name as the key in this case. This would also allow for people to set their own name if wanted. It also sounds much more maintainable than uploading every single album image to your app. Also allow users to still use the original client id, just have a notice that it does not allow album arts.

**Comment by sll552** [comment]
There was #48 but it was closed by the creator.

Anyway I don't think it would have helped in your particular case. Please note that there is a limit of images to be uploaded in Discord (if I remember it right, about 150). And there is no public API to upload them, so you can't do (or at least should not do) it within the plugin code.
So in the best case you are masochistic enough and have a small enough music library that you could manually upload all your albums but I don't think that this makes much sense.

**Comment by Svarr** [comment]
So you have to upload the images to discord? Can't they be streamed or something?  
How does spotify do it?
