### ISSUE TITLE
Allow us to change the text of the Play/Pause icon

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#59]
**Describe the solution you'd like**
Allow us to change the text of the Play/Pause icon. I'd like to put my listen count there.

![image](https://user-images.githubusercontent.com/32050292/108017911-2c379980-6fe4-11eb-8ed2-c46decd54c5a.png)

**Comment by sll552** [comment]
Unfortunately this is not possible to change programmatically. Only the caption of the large picture can be changed (which you can do through settings)

**Comment by Rings4** [comment]
> 
> 
> Unfortunately this is not possible to change programmatically. Only the caption of the large picture can be changed (which you can do through settings)

Are you sure? It's possible using other discord rich presence software. I recall Winamp allowing such freedom, and my friend coded his own rich presence for VLC. You can see in the screenshot below he set the song state as well as the volume to the little icon.

![image](https://user-images.githubusercontent.com/32050292/108154975-fc53c900-70ab-11eb-9953-394b598d8eb1.png)

I believe you can add functionality here: https://github.com/sll552/DiscordBee/blob/master/DiscordBee.cs#L235

**Comment by sll552** [comment]
You are right, I am sorry, of course its possible. I will add it with the next version.

**Comment by sll552** [comment]
released in 1.4.1
