### ISSUE TITLE
Cant initialise discordbee

### ISSUE THREAD

**Issue by sirbonesbonesbones** [sll552/DiscordBee#63]
**Describe the bug**
When I add the plugin, an error pops up saying "Exception has been thrown by the target of an invocation." The first time i downloaded discordbee it worked properly but i deleted it once and downloaded it again and it does this.

**Screenshots**
![image](https://user-images.githubusercontent.com/81931719/113521507-e15bec00-9567-11eb-8435-cad666d21042.png)

**Environment (please complete the following information):**
 - MusicBee Version: [e.g. 3.2.6345]
 - Plugin Version: [e.g. 1.4.0]

**Additional context**
I noticed "discord-rpc-w32.dll" wasnt in the plugin folder and the site says I need it. I'm not sure why it's not there though.

**Comment by sll552** [comment]
Do you have the Windows Store version of MusicBee? Also please take a look at the error log (MusicBee -> Help -> Support ->Error log) if there is anything related to an exception. Did you try to close and reopen MusicBee after the error? 

The dll is not needed anymore, I forgot to remove this from the plugin site. Also is there a reason why you are using an older version of MusicBee? Current version should be 3.3 with 3.4 being released soon (https://getmusicbee.com/forum/index.php?topic=32142.msg189636#msg189636)

**Comment by sirbonesbonesbones** [comment]
Oh, no I have the installer edition of MusicBee. And it does say target invocation exception in the error log. Yes I did close and reopen Musicbee and I restarted my computer as well.

Also I did not realise I was using an older version, I just went off what it said on the website, oops.
![image](https://user-images.githubusercontent.com/81931719/113625503-036c7180-962f-11eb-9682-86e64aae0c1d.png) 
Ah okay I don't need the dll

**Comment by sll552** [comment]
> Also I did not realise I was using an older version, I just went off what it said on the website, oops.

I meant your version of MusicBee, in the initial message you stated that you are using 3.2.6345 which is old. The plugin version 1.4.0 is fine.

**Comment by sirbonesbonesbones** [comment]
OHH I'm sorry. I'll get the newst version of MusicBee to see if that'll make a difference.

**Comment by Svarr** [comment]
I have the same problem. Latest stable MusicBee and PlugIn version (downloaded both just a few minutes ago).

This is the full stack trace:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'DiscordRPC, Version=1.0.175.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at MusicBeePlugin.Plugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase)
   at #=z_aDAVc7sMkwkYxQETg==..ctor(#=zoKrwgApZgrrQua03HQ== #=zmYRlZmg=)```

Maybe there still is a dependency to the Discord RPC library?

**Comment by Svarr** [comment]
Ok, in my case it was mostly my own fault (who would've known...). I put all of the plugins files into a folder (to keep multiple plugins separated in case I add some in the future). MusicBee doesn't seem to look for plugins recursively (i.e. only in the Plugins folder but not subfolders), so DiscordBee didn't show up. That led me to use the "Add Plugin..." button which added a stump entry that couldn't initialise (see error in the post above). By looking into the MusicBee3Settings.ini I found out, that said entry referenced the Plugins folder in AppData\Roaming. MusicBee probably didn't copy all the files into that folder (or none if it was a Admin privileges thing).

Anyway, I fixed it by moving the files into the Plugins directory directly and removing the stump entry from the .ini file.

**Comment by sirbonesbonesbones** [comment]
I finally got it to work, I did what Svarr did and took the plugins out of the subfolder and it worked. Thank you!

**Comment by Chaython** [comment]
I'm using the newest MB patch https://getmusicbee.com/patches/MusicBee34_Patched.zip
I've tried this and another plugin like it. 
The other one [ https://github.com/maybeclean/musicbee-rich-presence ] could only sync icons to the discord api, but didn't show presence... This one doesn't seem to be doing anything.
I tried another one, that was dead from 2017, and it just gave a bunch of errors.
Sad.
