### ISSUE TITLE
stumbled upon these plugins with Album Art support, Is it possible?

### ISSUE THREAD

**Issue by feecof** [sll552/DiscordBee#64]
https://github.com/Kuunikal/mb_DiscordRichPresence
https://gitlab.com/cleaninfla/musicbee-rich-presence

i couldnt get them to work because i dont know how to compile them. But it would be nice if you could implement something like that in your future build.

**Comment by sll552** [comment]
Those plugin have the same limitations as this one. It is not possible to show arbitrary pictures (Album Art) with the current RichPresence. What these plugins allow is that you basically manually add all your art to a discord dev account. I consider this a non-usecase as its really cubersome for the user and the result won't be satisfactory.

More on this in #57

**Comment by sll552** [comment]
Ok, the 2nd one actually automates the upload, but this is most likely against Discord Terms of Service and relies on an auth token that might get revoked which would require a recompile of the plugin...
