### ISSUE TITLE
Virtual tags past 16 do not show in version 1.4.1

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#66]
**Describe the bug**
Virtual tags past 16 do not show in version 1.4.1. (I actually don't know if they worked before because I only just made my 17th and 18th virtual tags after installing 1.4.1.)

![Screenshot 2021-04-05 19 31 11](https://user-images.githubusercontent.com/32050292/113639178-9533a900-9646-11eb-871d-1df5a2f12053.png)

Shown in my screenshot, I have 18 virtual tags, 17 and 18 being identical.
Virtual tags 1-16 all work in discordbee, no problem, when used as [Virtual1] - [Virtual16] (it doesn't take the assigned names for some reason).
Virtual tags 17 and 18, however, simply show "[Virtual17]" or "[Virtual18]" when set in discordbee. 

![Screenshot 2021-04-05 19 36 59](https://user-images.githubusercontent.com/32050292/113639183-9c5ab700-9646-11eb-9191-9cc44e4bba58.png)

I tried setting virtual tags 17 and 18 in the 2 highlighted boxes, both to the same result:

![Screenshot 2021-04-05 19 26 28](https://user-images.githubusercontent.com/32050292/113639187-9ebd1100-9646-11eb-9e90-939db937d77b.png)

Using Musicbee 3.4.7536 P, Discordbee 1.4.1

**Comment by Rings4** [comment]
Okay, I think the issue isn't the update, but the fact that this plugin simply does not look for Virtual tags 17-32. I just checked placeholders and I see it stops at 16.

![Screenshot 2021-04-05 19 48 12](https://user-images.githubusercontent.com/32050292/113639783-f14afd00-9647-11eb-9f5c-8d39f7a7c096.png)

**Comment by sll552** [comment]
You can try this with https://ci.appveyor.com/api/buildjobs/c4ufcqg8srxti8v2/artifacts/DiscordBee-Release-update_mb_interface-126.zip

**Comment by Rings4** [comment]
> 
> 
> You can try this with https://ci.appveyor.com/api/buildjobs/c4ufcqg8srxti8v2/artifacts/DiscordBee-Release-update_mb_interface-126.zip

![image](https://user-images.githubusercontent.com/32050292/113797441-49086780-971f-11eb-97b3-9d57ed9a430e.png)

Hmm, it seems I need to update musicbee to use this plugin. I'll look for the latest beta (since I'm already using a version newer than the latest official release) and will post back.

**Comment by Rings4** [comment]
> 
> 
> You can try this with https://ci.appveyor.com/api/buildjobs/c4ufcqg8srxti8v2/artifacts/DiscordBee-Release-update_mb_interface-126.zip

It looks like my previous reply was incorrect as I see the latest official release was actually updated today! I've went ahead and installed it and it's working great! Virtual tag 17 works, and I see placeholders for 17-25, so I assume those would also all work. 

It's definitely a great improvement to be able to use Virtual tags 17-25 now! If you can manage to figure out how to implement Virtual tags 26-32 as well, I'll be really happy. You can make the virtual tags something easily distinguishable so that you can simply hunt down the values and figure out which fields correspond to which virtual tags. Something like below:

![image](https://user-images.githubusercontent.com/32050292/113798017-5a9e3f00-9720-11eb-9507-5b4c4e4acfd9.png)
