### ISSUE TITLE
Can I use plugins ?

### ISSUE THREAD

**Issue by Prateekkota** [sll552/DiscordBee#72]
Hey are the plugins which have like 100k downloads safe ?
Can I get banned from using those?

I really want to know please :(
I really want to know if these are safe or not.
![2021-04-30](https://user-images.githubusercontent.com/64154723/116641411-51ed0180-a98a-11eb-8cb3-8e42fa56e76e.png)

**Comment by sll552** [comment]
This is not a forum about betterdiscord
