### ISSUE TITLE
Allow the use of <year (yyyy)> tag natively

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#75]
Currently this tag cannot be used so we need to make a virtual tag. It would be great if this tag can be used natively so we won't have to waste an entire virtual tag just to display something MusicBee already has a tag for.

**Comment by sll552** [comment]
This should be working? 
![image](https://user-images.githubusercontent.com/6547809/131222455-32543c61-34bf-4d59-a336-54e0fef50b4c.png)

**Comment by Rings4** [comment]
> This should be working?
> ![image](https://user-images.githubusercontent.com/6547809/131222455-32543c61-34bf-4d59-a336-54e0fef50b4c.png)

Try adding an additional year tag to your flac file and making it eg. 2014-04-03. Discordbee will then not see the 2014 tag.

**Comment by sll552** [comment]
Ok now I understand the problem. I was not aware that there are two tags that hold the year and thought you meant the "Year" one. 

I will try to get it to work but this is a limitation of the API, because it doesn't get updated very often e.g. when such fields are added.

**Comment by Rings4** [comment]
> 
> 
> Ok now I understand the problem. I was not aware that there are two tags that hold the year and thought you meant the "Year" one.
> 
> I will try to get it to work but this is a limitation of the API, because it doesn't get updated very often e.g. when such fields are added.

Much appreciated. Reason for wanting the yyyy formatted version is to be able to put the year here since I normally don't put the total tracks number, and frankly I don't find it to be important information:
![image](https://user-images.githubusercontent.com/32050292/131232984-ebb7ed1c-5586-4496-b492-ad8f290eedb1.png)

**Comment by sll552** [comment]
I have added the missing fields, the field you were looking for is called "YearOnly" in the UI. I will do a release when a few other things are fixed but if you want to use it before you can grab the current version at https://ci.appveyor.com/api/buildjobs/i6i9m5k71hr21b6l/artifacts/DiscordBee-Release--149.zip

**Comment by Rings4** [comment]
> 
> 
> I have added the missing fields, the field you were looking for is called "YearOnly" in the UI. I will do a release when a few other things are fixed but if you want to use it before you can grab the current version at https://ci.appveyor.com/api/buildjobs/i6i9m5k71hr21b6l/artifacts/DiscordBee-Release--149.zip

Awesome, thanks a lot! I'm using your link, works great! This saves me a virtual tag that I can use for something else in the future.

Speaking of, any plans on increasing the limit of Virtual tags from 25 to 32?

**Comment by sll552** [comment]
> Speaking of, any plans on increasing the limit of Virtual tags from 25 to 32?

This should also be working with this version

**Comment by Andrewsch24** [comment]
> I have added the missing fields, the field you were looking for is called "YearOnly" in the UI. I will do a release when a few other things are fixed but if you want to use it before you can grab the current version at https://ci.appveyor.com/api/buildjobs/i6i9m5k71hr21b6l/artifacts/DiscordBee-Release--149.zip

Hey, just wanted to say that I wanted to download this version but this link displays an access denied for me.
