### ISSUE TITLE
Configure... elements not visible

### ISSUE THREAD

**Issue by sorwu** [sll552/DiscordBee#80]
**Describe the bug**
When opening the Configure... button under discordbee's plugin preferences, the window size is only adjustable left & right. I think everything after the first row may be hidden by the bottom settings. The buttons also don't show the text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the preferences
2. click Plugins button
3. click Configure... button

**Expected behaviour**
When opening the settings I see no button text and only the first line of the options viewable. (see below)

**Screenshots**
![image](https://user-images.githubusercontent.com/43003141/120357847-defde000-c2d3-11eb-890d-8e55475abd54.png)
my computer with a 3000x2000 resolution

![image](https://user-images.githubusercontent.com/43003141/120357698-ba096d00-c2d3-11eb-8a03-7cba49a063e3.png)
someone else with a similar issue

**Environment (please complete the following information):**
 - MusicBee Version: [3.4.7805]
 - Plugin Version: [1.4.2]

**Comment by sll552** [comment]
Do you have any kind of scaling enabled in windows? I have no monitor with such a resolution to test it, so this is the only thing I could think of. If so try to set it to 100% and try again.
The settings window is only resizeable in one way by design and should also open with a hardcoded minimal size that fits all elements.

**Comment by sorwu** [comment]
It's set to 200 by default with my pc, I'll change it to 200 and do that.

**Comment by OchiiaSyc** [comment]
I was having this same issue and by changing windows display scaling back to 100% fixed it. So whenever I want to change something in there, I have to change the scaling back to 100%.

**Comment by sll552** [comment]
Ok, so at least there is a workaround and it seems that the issue is indeed connected to windows internal scaling. I will of course try to fix this.

**Comment by SkytAsul** [comment]
Any news on this?

**Comment by sll552** [comment]
I am quite busy at the moment, but I have not forgotten about it.

**Comment by sll552** [comment]
For a quick fix I tried to get the current UI to scale better, I tried with 150% and it looked OK. Could anyone with a HighDPI display test the following build? https://ci.appveyor.com/api/buildjobs/akpeufchrqfic3p1/artifacts/DiscordBee-Release--142.zip

**Comment by SkytAsul** [comment]
![image](https://user-images.githubusercontent.com/28827134/131247684-b7cbceac-53b6-4a83-aad9-e86610bb5b04.png)
Yayyy!
I'm with 175%
