### ISSUE TITLE
[Enhancement] Option to disable track # visibility

### ISSUE THREAD

**Issue by AffeN01** [sll552/DiscordBee#85]
When shuffling music or listening to playlists, it looks weird when the track count is displayed.
An option to completely disable the visibility of track count/track number would be awesome.

**Comment by sll552** [comment]
You should be able to accomplish this by deleting the placeholders in options.

**Comment by AffeN01** [comment]
> You should be able to accomplish this by deleting the placeholders in options.

Hmm... Didn't work at first, but I had an older version installed. Works fine with the latest release!
