### ISSUE TITLE
Show current song playing directly into the status

### ISSUE THREAD

**Issue by itsbenchang** [sll552/DiscordBee#88]
Would it be possible to have it show the status as [Artist] - [TrackTitle] instead of Playing MusicBee with the Note icon?

**Comment by sll552** [comment]
I am not really sure to which icon you are referring. With the latest version auf this plugin every text field that is possible to change, can be changed.
The presence should look  like this with stock settings:
![Small presence](https://i.imgur.com/zRfqSki.png)

The "MusicBee" at the top cannot be changed dynamically as this is the title of the registered Discord app.

**Comment by itsbenchang** [comment]
I think your last sentence, answers the request.
This was the status I was hoping that could be changed. 
![image](https://user-images.githubusercontent.com/19923593/134760246-e131398f-8612-4f5d-a87c-b9716223b253.png)

Thanks for replying. Great work on the app!
