### ISSUE TITLE
Make <Time> accessible natively

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#91]
Congratulations on finally releasing 2.0.0 with the album covers! Just wanted to make a quick little feature request since the fork I was using had this:

Add \<Time> (or Duration) to be a natively usable tag so we don't have to make a virtual tag just to display the song's duration.

That's all, thanks again for maintaining this plugin and improving it!

**Comment by sll552** [comment]
What format should be used for the time? Or do you want seperate tags for minutes and seconds. 

It should be no problem to add something like "Duration = 3:28", is this what you would expect?

**Comment by Rings4** [comment]
> What format should be used for the time? Or do you want seperate tags for minutes and seconds.
> 
> It should be no problem to add something like "Duration = 3:28", is this what you would expect?

Yes, 3:28 is perfect. The same as musicbee's internal "time" tag. I currently just use a virtual tag that does they but it feels like a waste of a virtual tag when it's just a single value that's already baked in to musicbee.
