### ISSUE TITLE
Pre-Upload Assets from current playlist

### ISSUE THREAD

**Issue by sll552** [sll552/DiscordBee#94]
Option to upload artwork from the next x titles in the playlist so they are available to display when the title actually starts playing.

**Comment by Svarr** [comment]
Is it just me or does the upload now work instantly? Yesterday the presence had shown the (new) album art right away.

**Comment by VelocityRa** [comment]
It takes many minutes for me.
CDN uploads are fast but the asset list is very slow to update.
Pre-uploading seems essential for this feature to be usable unfortunately, unless you only listen to the same few albums.

**Comment by VelocityRa** [comment]
I think I'm going to try implementing this.
If you want, tell me your Discord so we can discuss it (using GitHub for this seems inefficient).

**Comment by sll552** [comment]
you can reach me at derTyp#0524

**Comment by VelocityRa** [comment]
Ok sent you a friend request.
No PR yet but I have something that seems to work fine btw.
