### ISSUE TITLE
[Duration] placeholder removes all 0's from value

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#97]
![Screenshot 2021-11-07 01 08 45 firefox](https://user-images.githubusercontent.com/32050292/140633128-be276bca-a0e7-4986-81c9-35d84a295742.png)
![Screenshot 2021-11-07 01 08 59 MusicBee](https://user-images.githubusercontent.com/32050292/140633129-ac9d41eb-860e-42ea-8eb8-39dbfd97252c.png)

The above should be 2:02 (2 minutes, 2 seconds).

![Screenshot 2021-11-07 01 09 49 firefox](https://user-images.githubusercontent.com/32050292/140633134-ca89b803-125e-445c-86fc-32bf0033ba61.png)

The above should be 2:06.

Small issue, hope it can be addressed easily. Thanks again for your work!

**Comment by sll552** [comment]
Oh wow sry for that, I guess thats what you get when pushing stuff without proper testing it...
