### ISSUE TITLE
Default back to default logo when new track with different artwork starts

### ISSUE THREAD

**Issue by Rings4** [sll552/DiscordBee#98]
Currently when a new track starts, it takes about 1 minute for the artwork to actually display, and you need to update the rich presence for it to actually display (pause/unpause or change volume). It looks like this while the artwork is not yet displaying:

![Screenshot 2021-11-07 01 47 14 chrome](https://user-images.githubusercontent.com/32050292/140636227-5dc74290-6cec-4516-afb6-a4ffef159995.png)

Instead, if the artwork can default back to the default logo during said downtime, there won't be a lack of image.

And for when you implement your planned enhancement of pre-uploading artwork of upcoming songs from the queue, it would still be nice for this to be implemented because if you just decide to listen to a new song on the spot, it still won't have enough time to have uploaded the artwork, so it will still show a missing artwork placeholder.

**Comment by sll552** [comment]
I can not reproduce this, and there should be logic to prevent this from happening. The expected behavior (and the actual behavior in my testing) is that the logo is shown until the artwork is successfully uploaded.

In other issues you mentioned a fork you were using, is this still the case. If not please list the exact steps and state of your discord app (the assets in the dev console).

**Comment by Rings4** [comment]
> 
> 
> I can not reproduce this, and there should be logic to prevent this from happening. The expected behavior (and the actual behavior in my testing) is that the logo is shown until the artwork is successfully uploaded.
> 
> In other issues you mentioned a fork you were using, is this still the case. If not please list the exact steps and state of your discord app (the assets in the dev console).

I stopped using that fork since updating to 2.0.0 of your plugin. I simply used the same ID I had already made for that fork, which thus allowed me to use the assets I had created to replace the default ones this plugin would have otherwise created.

One thing I suspect may be causing different behviour with me is that I didn't replace the mb_DiscordBee.dll.config file. My file is from September 16, 2021 (not sure which version) and has the following contents:

```
<?xml version="1.0"?>
<configuration>
	<startup/>
</configuration>
```

The current 2.0.2 version's file has the following contents:

```
<?xml version="1.0"?>
<configuration>
	<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/></startup></configuration>

```

A lot of my friends have been struggling to get artwork to display, not to mention having duplicate rich presences showing and other weird occurrences. Meanwhile, mine has been working without a hitch from the start, since updating to 2.0.1. Do you think the use of this old config file may be the reason mine just seems to work normally without issue?

**Comment by sll552** [comment]
As it is really hard to debug those issues without being able to reproduce this, I am going to add logging to the next release, to get a clue whats happening. Until that unfortunately I have to ask for your patience.
